version: '3.8'

services:

  user-service:
    image: sonishivam1402/zyaka-express-user-service
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}

  auth-service:
    image: sonishivam1402/zyaka-express-auth-service
    ports:
      - "5001:5001"
    environment:
      USER_SERVICE_URL: http://user-service:5000
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}

  restaurant-service:
    image: sonishivam1402/zyaka-express-restaurant-service
    ports:
      - "5002:5002"
    environment:
      MONGO_URI: ${MONGO_URI}

  api-gateway:
    image: sonishivam1402/zyaka-express-api-gateway
    ports:
      - "8080:8080"
    environment:
      USER_SERVICE_URL: http://user-service:5000
      AUTH_SERVICE_URL: http://auth-service:5001
      RESTAURANT_SERVICE_URL: http://restaurant-service:5002
    depends_on:
      - user-service
      - auth-service
      - restaurant-service

