version: '3.8'

services:

  user-service:
    build: ./services/user-service
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://ZyakaExpress_owner:npg_0xL5mrRpXHCW@ep-rough-boat-a8qzkm9n-pooler.eastus2.azure.neon.tech/ZyakaExpress?sslmode=require
      JWT_SECRET: efa29e47afe57f3826e834266d3224842f88ae08859e4736ea4e444e4ba0b081

  auth-service:
    build: ./services/auth-service
    ports:
      - "5001:5001"
    environment:
      USER_SERVICE_URL: http://user-service:5000
      JWT_SECRET: efa29e47afe57f3826e834266d3224842f88ae08859e4736ea4e444e4ba0b081

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      USER_SERVICE_URL: http://user-service:5000
      AUTH_SERVICE_URL: http://auth-service:5001
    depends_on:
      - user-service
      - auth-service


