name: Build & Push Docker Images

on:
  push:
    branches:
      - main  # Triggers on push to main branch

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: user-service
            path: services/user-service
          - name: auth-service
            path: services/auth-service
          - name: restaurant-service
            path: services/restaurant-service
          - name: api-gateway
            path: api-gateway

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.path }}
          file: ./${{ matrix.path }}/Dockerfile
          push: true
          tags: sonishivam1402/zyaka-express-${{ matrix.name }}:latest

      - name: Trigger Render Deploy for ${{ matrix.name }}
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_${{ matrix.name | upper | replace('-', '_') }} }}
